{
 "title": "App Metrics",
 "tags": [ "aptible-generated" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "show tag values WITH key=\"environment\""
   },
   {
    "name": "app",
    "label": "App",
    "query": "show tag values WITH key = \"app\" WHERE environment =~ /^$environment$/"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "show tag values WITH key=\"service\" WHERE environment =~ /^$environment$/ AND app =~ /^$app$/"
   },
   {
    "name": "host",
    "label": "Container",
    "query": "SELECT \"host\",last(\"memory_rss_mb\") FROM \"metrics\" WHERE environment =~ /^$environment$/ AND app =~ /^$app$/ AND service =~ /^$service$/ AND $timeFilter GROUP BY \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_app - $tag_service - $tag_host",
     "query": "SELECT MAX(\"memory_rss_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"app\" =~ /^$app$/\nAND \"service\" =~ /^$service$/\nAND \"host\" =~ /^$host$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"app\", \"service\", \"host\"\n        fill(null)"
    },
    {
     "alias": "$tag_environment - $tag_app - $tag_service - $tag_host (Limit)",
     "query": "SELECT MAX(\"memory_limit_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"app\" =~ /^$app$/\nAND \"service\" =~ /^$service$/\nAND \"host\" =~ /^$host$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"app\", \"service\", \"host\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_app - $tag_service - $tag_host",
     "query": "SELECT MAX(\"memory_rss_mb\") / MAX(\"memory_limit_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"app\" =~ /^$app$/\nAND \"service\" =~ /^$service$/\nAND \"host\" =~ /^$host$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"app\", \"service\", \"host\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_app - $tag_service - $tag_host",
     "query": "SELECT MEAN(\"milli_cpu_usage\") / 1000\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"app\" =~ /^$app$/\nAND \"service\" =~ /^$service$/\nAND \"host\" =~ /^$host$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"app\", \"service\", \"host\"\n        fill(null)"
    },
    {
     "alias": "$tag_environment - $tag_app - $tag_service - $tag_host (Limit)",
     "query": "SELECT MAX(\"memory_limit_mb\") / 4096\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"app\" =~ /^$app$/\nAND \"service\" =~ /^$service$/\nAND \"host\" =~ /^$host$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"app\", \"service\", \"host\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_app - $tag_service - $tag_host",
     "query": "SELECT (MEAN(\"milli_cpu_usage\") / 1000) / (MAX(\"memory_limit_mb\") / 4096)\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"app\" =~ /^$app$/\nAND \"service\" =~ /^$service$/\nAND \"host\" =~ /^$host$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"app\", \"service\", \"host\"\n        fill(null)"
    }
   ]
  }
 ]
}