{
 "title": "Database Metrics",
 "tags": [ "aptible-generated" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "show tag values WITH key=\"environment\""
   },
   {
    "name": "database",
    "label": "Database",
    "query": "show tag values WITH key = \"database\" WHERE environment =~ /^$environment$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT MAX(\"memory_rss_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    },
    {
     "alias": "$tag_environment - $tag_database (Limit)",
     "query": "SELECT MAX(\"memory_limit_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT MAX(\"memory_rss_mb\") / MAX(\"memory_limit_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT MEAN(\"milli_cpu_usage\") / 1000\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    },
    {
     "alias": "$tag_environment - $tag_database (Limit)",
     "query": "SELECT MAX(\"memory_limit_mb\") / 4096\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT (MEAN(\"milli_cpu_usage\") / 1000) / (MAX(\"memory_limit_mb\") / 4096)\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT MAX(\"disk_usage_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    },
    {
     "alias": "$tag_environment - $tag_database (Limit)",
     "query": "SELECT MAX(\"disk_limit_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT MAX(\"disk_usage_mb\") / MAX(\"disk_limit_mb\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT MAX(\"disk_read_iops\") + MAX(\"disk_write_iops\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_environment - $tag_database",
     "query": "SELECT MAX(\"disk_read_kbps\") + MAX(\"disk_write_kbps\")\nFROM \"metrics\"\nWHERE $timeFilter\nAND \"environment\" =~ /^$environment$/\nAND \"database\" =~ /^$database$/\nGROUP BY\n        time($__interval),\n        \"environment\", \"database\"\n        fill(null)"
    }
   ]
  }
 ]
}